# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc20e724c7afc197cc8c53b610969833c0712e2033b75dcb8240d72ed466dca20615b578410dc29c22a3ae50384d31f04a6b7bd3524686f950515db78fbb3cd5

test:
  secret_key_base: 4f58dd467be1e892cec88ecef140c42e0e1639016043dbeab50133f5900a344ebefcdebe8b1002dc5e4ed6e6d08d73821b1dad6678968e3dbef088af3f7fb0f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
